### ISSUE TITLE
DOC: Broken links in CONTRIBUTING.md

### ISSUE THREAD

**Issue by rossbar** [numpy/.github#1]
The links to the [development workflow](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html) and [conventions for commit messages](https://docs.scipy.org/doc/numpy/dev/gitwash/development_workflow.html#writing-the-commit-message) are broken.

It's simple enough to fix the links, but there is also a CONTRIBUTING.md in numpy/numpy/.github which is identical except that the links are not broken. If there is a way to keep the two files in sync that might be a better fix so that both files don't have to be changed if the link targets change again.

**Comment by rgommers** [comment]
IIRC we checked before and there isn't a good way of keeping it all in sync automatically

**Comment by rossbar** [comment]
If the .github directory were removed from the numpy repo (i.e. `numpy/numpy/.github`), would everything default to the organization .github repository (i.e. `numpy/.github)? That might be a way to have only one copy of the files, though perhaps it's desirable to have separate github behavior at the organization and project level.

Just thought I'd bring it up in case it hadn't been discussed.
