### ISSUE TITLE
Change default branch

### ISSUE THREAD

**Issue by mattip** [numpy/.github#4]
The default branch for this repo should match the default branch for the other repos so that the links in the [community standards (for instance numpy/numpy's](https://github.com/numpy/numpy.org/community) pages work. The link there refers to `main` where this repo uses `master`. Are there other repos that also need to move to `main`?

@rossbar is there a recommended way to update the default branch?

**Comment by seberg** [comment]
I think you can just change it in the settings.  There are 3 ones that need to move also: numpy-financial, bitgenerators, and numpy-surveys it seems.  I think we can all simply change those (there are a few archived ones, that I don't think matter).

Should I do that?

**Comment by mattip** [comment]
Yes please. I don't have permissions for all the repos.

**Comment by seberg** [comment]
Ah OK, done.

**Comment by mattip** [comment]
Thanks @seberg. closing.
